openapi: 3.0.0
info:
  version: 1.0.0
  title: Back End Demonstration API
  description: A simple blog API.
  contact: 
    name: Ivan
    email: Ivan@vtc.edu.hk
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: 'https://feec368b-f2cd-4c78-ba6d-d66f03597562-00-2xj5l7c94qwox.sisko.repl.co:3000/api/v1'
    description: Development server
tags:
  - name: Users
    description: API endpoints for user management.
  - name: Hotels
    description: Access and perform CRUD operations on hotel entries.
  - name: Login
    description: login user account
      

paths:
  /users/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
        description: Numeric id of the user
    get:
      tags:
        - Users
      description:
        Get user by id.
      responses:
        '200':
          description: user record.
          content:
            application/json:
              schema:
               type: object
               properties:              
               $ref: ./user.json#/definitions/user
        '404':
          description: User was not found in the DataBase.
    put:
      tags:
        - Users
      description:
        Update user by ID.
      requestBody:
        description: Modify user record
        required: true
        content:
          application/json:
            schema:
              $ref: ./user.json#/definitions/user
      responses:
        '200':
          description: View of an user record.
        '404':
          description: User was not found in the DB.
    delete:
      tags:
        - Users
      description:
        Delete user by ID.
      responses:
        '200':
          description: View of user record.
        '404':
          description: User was not found in the DB.

  /users/:
    parameters:
    - in: query
      name: limit
      schema:
        type: integer
      description: no. of  records to display with 10 records/page
    - in: query
      name: page
      schema:
        type: integer
      description: starting page no.to display
    - in: query
      name: fields
      schema:
        type: string
      description: fields to display
    - in: query
      name: q
      schema:
        type: string
      description: specifiy the search criteria  for either fields of username or email
    get:
      tags:
        - Users
      description: Get all users
      responses:
       '200':
         description: OK
         content:
           application/json:
             schema:
               type: array               
               $ref: ./user.json#/definitions/user
       '404':
         description: Not Found  
    post:
      tags:
       - Users
      description: Create a new user
      requestBody:
        description: A new user data
        required: true
        content:
          application/json:
            schema:
              $ref: ./user.json#/definitions/user
      responses:
        '201':
          description: User created
        '400':
          description: Bad request
  

        
  /hotel/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
        description: Numeric id of the hotel
    get:
      tags:
        - Hotels
      description:
        Get hotel by id.
      responses:
        '200':
          description: View of hotel record.
        '404':
          description: hotel was not found in the DB.
    put:
      tags:
        - Hotels
      description:
        Update hotel by ID.
      requestBody:
        description: A new hotel data
        required: true
        content:
          application/json:
            schema:
              $ref: ./hotel.json#/definitions/hotel     
      responses:
        '200':
          description: View of an hotel record.
        '404':
          description: hotel  was not found in the DB.
    delete:
      tags:
        - hotels
      description:
        Delete hotel  by ID.
      responses:
        '200':
          description: View of an hotel  record.
        '404':
          description: hotel  was not found in the DB.

  /hotel/: 
    get:
      tags:
      - hotel
      description: Get all hotel
      responses:
        '200':
          description: hotel record.
          content:
            application/json:
             schema:
               type: object 
               properties:   
                 id:
                   type: integer
                   description: The id of hotel. 
                 title:
                   type: string
                   description: The title of hotel.
                 imageurl:
                   type: string
                   description: The link to image of hotel.
                 summary:
                   type: string
                   description: summary of hotels
                 agencyid:
                   type: integer 
                   description: The id of  agency.  
                 links:
                   type: uri array object
                   description: include four links to likes,fav,msg and self with articleid respectively eg.articleid=1 [{"likes":"https://xxx:3000/api/v1/hotel/1/likes"},{"fav":"https://xxx:3000/api/v1//hotel/1/fav"},{"msg":"https://xxx:3000/api/v1//hotel/1/msg"},{"self":"https:xxx:3000/api/v1//hotel/1"}]
          '404':
            description: Not Found  
    post:
      tags:
       - hotel
      description: Create a new hotel
      requestBody:
        description: A new hotel data
        required: true
        content:
          application/json:
            schema:
              $ref: ./hotel.json#/definitions/hotel
      responses:
        '201':
          description: Articles created
        '400':
          description: Bad request


          